apiVersion: v1
kind: Pod
metadata:
  name: soc-attacker
  namespace: mini-soc
  labels:
    app: soc-attacker
spec:
  containers:
  - name: attacker
    image: kalilinux/kali-rolling
    command: ["/bin/bash", "-c", "sleep infinity"]
    tty: true
    stdin: true